// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUser = "sys_user"

// SysUser 用户信息表
type SysUser struct {
	ID    int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	UID   string    `gorm:"column:uid;not null;comment:唯一标识" json:"uid"`                  // 唯一标识
	Roles []SysRole `gorm:"foreignKey:uid;joinForeignKey:user_id;joinReferences:role_id;many2many:sys_user_role;references:rid" json:"roles"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
