// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRole = "sys_role"

// SysRole 角色信息表
type SysRole struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Rid      string    `gorm:"column:rid;not null;comment:唯一标识" json:"rid"`                  // 唯一标识
	RoleName string    `gorm:"column:role_name;not null;comment:角色名称" json:"role_name"`      // 角色名称
	Users    []SysUser `gorm:"foreignKey:rid;joinForeignKey:role_id;joinReferences:user_id;many2many:sys_user_role;references:uid" json:"users"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
